### ISSUE TITLE
我很喜欢这个rss阅读器 希望能修改几处交互的地方

### ISSUE THREAD

**Issue by 1a57danc3** [djyde/everfeed#2]
1 ： 左侧的rss目录列表  希望移至最左边  右侧的阅读部分  文章部分稍微右移一点   现在的目录太右边了   看文章的时候  就一直盯着显示屏的右侧部分 比较吃力 这点可以参考digg reader
2： 希望有时间更新一下bootstrap  扁平化界面 如果没时间   现在的UI也很好看了
3： 增加设置功能 比如字体调节 背景调节

加油

**Comment by 1a57danc3** [comment]
还有就是移动式设备的响应式网页兼容问题   平时喜欢在车上看文章  就只能用手机了

**Comment by djyde** [comment]
谢谢支持
我终于高考完了
终于能更新了

**Comment by 1a57danc3** [comment]
大基佬~  ↖(￣▽￣")

**Comment by 1a57danc3** [comment]
这些应该对你有帮助 响应式导航 http://www.bootcss.com/p/responsive-nav.js/    扁平ui  http://www.bootcss.com/p/flat-ui/
