### ISSUE TITLE
订阅文章不能显示    

### ISSUE THREAD

**Issue by 1a57danc3** [djyde/everfeed#3]
翻墙之后正常

**Comment by djyde** [comment]
google子域名全被封，之后你懂的，rss解析部分用到了google reader的API

**Comment by JokerQyou** [comment]
这个项目可能会有所帮助：https://github.com/devongovett/reader

**Comment by 1a57danc3** [comment]
> 这个项目可能会有所帮助：https://github.com/devongovett/reader 
> 

thx
